// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYuBpiIYImXX7B-Xdur21q_n-OQhrsZK8',
    appId: '1:435782441404:web:f801876d0253af9dfe73b9',
    messagingSenderId: '435782441404',
    projectId: 'dietitian-a0650',
    authDomain: 'dietitian-a0650.firebaseapp.com',
    storageBucket: 'dietitian-a0650.firebasestorage.app',
    measurementId: 'G-ZDHQSWMCRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAL5LFX_EhgjCoTN_wMpGjRNU_9w_1I24',
    appId: '1:435782441404:android:fc37b432c055c113fe73b9',
    messagingSenderId: '435782441404',
    projectId: 'dietitian-a0650',
    storageBucket: 'dietitian-a0650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ouVx5eW2MiiJOcbcRz3xIJ9ZCDw2QCM',
    appId: '1:435782441404:ios:d0958edbbe8f4894fe73b9',
    messagingSenderId: '435782441404',
    projectId: 'dietitian-a0650',
    storageBucket: 'dietitian-a0650.firebasestorage.app',
    iosClientId: '435782441404-km9nsj7bgv9aak7sil2k78640jers2cb.apps.googleusercontent.com',
    iosBundleId: 'com.examplegukos.dietitian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6ouVx5eW2MiiJOcbcRz3xIJ9ZCDw2QCM',
    appId: '1:435782441404:ios:ead7ef72cca78d2dfe73b9',
    messagingSenderId: '435782441404',
    projectId: 'dietitian-a0650',
    storageBucket: 'dietitian-a0650.firebasestorage.app',
    iosClientId: '435782441404-crleuv8flv5ni9nvmjjrs95boju3vbui.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietitian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYuBpiIYImXX7B-Xdur21q_n-OQhrsZK8',
    appId: '1:435782441404:web:d9df5f429c38199efe73b9',
    messagingSenderId: '435782441404',
    projectId: 'dietitian-a0650',
    authDomain: 'dietitian-a0650.firebaseapp.com',
    storageBucket: 'dietitian-a0650.firebasestorage.app',
    measurementId: 'G-7T9GW6MYXS',
  );

}