// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMccoqu6p4g3JskSwYHt3rWITaSzx-Qdc',
    appId: '1:226138301158:web:2235c604f125844f2c9127',
    messagingSenderId: '226138301158',
    projectId: 'prototype-7ae6a',
    authDomain: 'prototype-7ae6a.firebaseapp.com',
    storageBucket: 'prototype-7ae6a.firebasestorage.app',
    measurementId: 'G-950583CCX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYUmtxl9GBE7GV6ocEm4qRCqaR5NPTG-g',
    appId: '1:226138301158:android:992412d5954c34ef2c9127',
    messagingSenderId: '226138301158',
    projectId: 'prototype-7ae6a',
    storageBucket: 'prototype-7ae6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgvRRqsOIrEEhPHQqPUCrkn-qRWRqrU4k',
    appId: '1:226138301158:ios:1ed2ed4e7582ab7a2c9127',
    messagingSenderId: '226138301158',
    projectId: 'prototype-7ae6a',
    storageBucket: 'prototype-7ae6a.firebasestorage.app',
    iosBundleId: 'com.example.prototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgvRRqsOIrEEhPHQqPUCrkn-qRWRqrU4k',
    appId: '1:226138301158:ios:1ed2ed4e7582ab7a2c9127',
    messagingSenderId: '226138301158',
    projectId: 'prototype-7ae6a',
    storageBucket: 'prototype-7ae6a.firebasestorage.app',
    iosBundleId: 'com.example.prototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMccoqu6p4g3JskSwYHt3rWITaSzx-Qdc',
    appId: '1:226138301158:web:0a0ab6c618bc059c2c9127',
    messagingSenderId: '226138301158',
    projectId: 'prototype-7ae6a',
    authDomain: 'prototype-7ae6a.firebaseapp.com',
    storageBucket: 'prototype-7ae6a.firebasestorage.app',
    measurementId: 'G-71K2NCHGFX',
  );

}